### ISSUE TITLE
Issue with opening Content Slots

### ISSUE THREAD

**Issue by nathanhemesath** [redvanworkshop/sfcc-devtools#5]
#### Overview:
When clicking on a **Content Slot** comment, the correct label will show, but the button is missing.
I'm wondering if it's because of the siteID missing from the comment, so the code below doesn't build the slotURL correctly. 
But it should still build the button, so I'm at a loss of what it could be exactly.

`if (props.type === 'slot' && props.id && domain && siteID)`

![content-slot-no-woring](https://user-images.githubusercontent.com/7455788/79618778-a0f22c80-80d0-11ea-94a4-16cab56a11b2.png)

**Comment by manifestinteractive** [comment]
@nancyhstorey I was able to sort out a solution after talking this over with @evechey.  Seems the actual issue here was that the `siteId` I was trying to fetch from the URL could possibly not actually be the correct `siteId` needed.

The correct solution here was to check for the siteID in a pre-existing javascript variable that should exist on all SFCC sites `CQuotient.siteId`.

There is a new release that just went out today, that should be approved and available for download soon for both Chrome and Firefox.

If you would like early access to this new version, you can download the extension manually using the [Manual Install](https://github.com/redvanworkshop/sfcc-devtools#manual-install) notes in the README.
